### PR TITLE
Crab env

### PR DESCRIPTION
**Pull request by hujw77**

### CODE REVIEW

**Comment by hamidroohi92** [comment]
Why the KOI is not in this PR?

**Comment by hackfisher** [comment]
> Why the KOI is not in this PR?
> 
> 

Echo said different chains will have different contract addresses.

So unfortunately, current ui for crab cannot reuse koi config. Supporting for chain switch is not enough:(

Smart contract needs update when switching chains.

Probably still deploy to different url, as we might not want hack/customize too much in the ui?

**Comment by hamidroohi92** [comment]
So why don't we also switch to a different contract address when switching the chain? like logo and title?

**Comment by hamidroohi92** [comment]
> So why don't we also switch to a different contract address when switching the chain? like logo and title?

We can have a config file and according to the connected chain, we can read the contract address from the.env file. How do you think I go on it and fix it?

**Comment by hackfisher** [comment]
> > So why don't we also switch to a different contract address when switching the chain? like logo and title?
> 
> 
> 
> We can have a config file and according to the connected chain, we can read the contract address from the.env file. How do you think I go on it and fix it?
> 
> 

Yes, That's good idea, go on with a PR please

**Comment by hamidroohi92** [comment]
> > > So why don't we also switch to a different contract address when switching the chain? like logo and title?
> > 
> > 
> > We can have a config file and according to the connected chain, we can read the contract address from the.env file. How do you think I go on it and fix it?
> 
> Yes, That's good idea, go on with a PR please

Ok. Give me the koi contract address please

**Comment by fewensa** [comment]
> So why don't we also switch to a different contract address when switching the chain? like logo and title?

Agree this.

**Comment by hackfisher** [comment]
> > > > So why don't we also switch to a different contract address when switching the chain? like logo and title?
> 
> > > 
> 
> > > 
> 
> > > We can have a config file and according to the connected chain, we can read the contract address from the.env file. How do you think I go on it and fix it?
> 
> > 
> 
> > Yes, That's good idea, go on with a PR please
> 
> 
> 
> Ok. Give me the koi contract address please

https://github.com/ringecosystem/vote.ringdao.com/blob/main/.env.koi


Contracts for Darwinia not deployed yet, can set to koi addresses for placeholder and change later.

**Comment by fewensa** [comment]
> > > > So why don't we also switch to a different contract address when switching the chain? like logo and title?
> > > 
> > > 
> > > We can have a config file and according to the connected chain, we can read the contract address from the.env file. How do you think I go on it and fix it?
> > 
> > 
> > Yes, That's good idea, go on with a PR please
> 
> Ok. Give me the koi contract address please

https://github.com/ringecosystem/vote.ringdao.com/blob/c3eb588ce2bd9e33d8736f53ee7e50aa6a6e86ac/.env.koi#L4-L11

I think you can direct use .env.koi file, right @hujw77 ?

**Comment by hackfisher** [comment]
Please note that current ci/cd is copying from koi env file.

**Comment by hamidroohi92** [comment]
I think it is a good idea to make the structure and make a WIP PR and then complete it after all data is fixed. I will start since now

**Pull request closed without merging**
