### PR TITLE
Add Darwinia Koi and Crab chain

### PR DESCRIPTION
**Pull request by hamidroohi92**
This PR is related to issue No 13 and targets adding darwinia, Crab and Koi networks

### CODE REVIEW

**Comment by nblogist** [comment]
will close #13  & #14

**Comment by boundless-forest** [comment]
image

image

Nice, the switch network works for me. However, I noticed that the balance display has some issues; please check it.

**Comment by hamidroohi92** [comment]
Ok. I will check it and fix the problem

**Comment by hackfisher** [comment]
Replaced by https://github.com/ringecosystem/vote.ringdao.com/pull/22

**Pull request closed without merging**
